[tool.poetry]
name = "nixops_gcp"
version = "1.0"
description = "NixOps backend for Google Cloud Platform"
authors = ["Evgeny Egorochkin <phreedom@yandex.ru>"]
maintainers = ["Amine Chikhaoui <amine@chikhaoui.org>"]
license = "MIT"
include = [ "nixops_gcp/nix/*.nix" ]

[tool.poetry.dependencies]
python = "^3.9, <3.11"
apache-libcloud = "^3.2.0"
cryptography = "^3.1.1"
nixops = {git = "https://github.com/rdparker/nixops.git", rev = "master"}
nixos-modules-contrib = {git = "https://github.com/rdparker/nixos-modules-contrib.git", rev = "master"}

[tool.poetry.dev-dependencies]
nose = "^1.3.7"
mypy = "^0.812"
black = "^19.10b0"

[tool.poetry.plugins."nixops"]
gcp = "nixops_gcp.plugin"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
